# Long datasets are not stored in the primary github repository.
# If you want to run them, clone http://curtis.ml.cmu.edu/git/tensorlog-datasets.git
# and place the path here:
#DATASETS:=/home/krivard/projects/tensorlog/tensorlog-datasets

# By default, the cross-compile tests will run all available target
# language configurations. If you want to limit the ones you run, add
# those preferences here: e.g. "tensorflow sparse"
XCOMP_FILTER:=